spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydiary
    username: chan
    password: helloworld
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
